export const countryFlags: Record<string, string> = {
  'Brazil': '🇧🇷',
  'Argentina': '🇦🇷',
  'France': '🇫🇷',
  'Germany': '🇩🇪',
  'Spain': '🇪🇸',
  'Portugal': '🇵🇹',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Mexico': '🇲🇽',
  'USA': '🇺🇸',
  'United States': '🇺🇸',
  'Canada': '🇨🇦',
  'Switzerland': '🇨🇭',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Croatia': '🇭🇷',
  'Uruguay': '🇺🇾',
  'Colombia': '🇨🇴',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'Korea Republic': '🇰🇷',
  'Australia': '🇦🇺',
  'Saudi Arabia': '🇸🇦',
  'Morocco': '🇲🇦',
  'Senegal': '🇸🇳',
  'Ghana': '🇬🇭',
  'Cameroon': '🇨🇲',
  'Nigeria': '🇳🇬',
  'Tunisia': '🇹🇳',
  'Iran': '🇮🇷',
  'Qatar': '🇶🇦',
  'Ecuador': '🇪🇨',
  'Chile': '🇨🇱',
  'Peru': '🇵🇪',
  'Serbia': '🇷🇸',
  'Poland': '🇵🇱',
  'Denmark': '🇩🇰',
  'Sweden': '🇸🇪',
  'Italy': '🇮🇹',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Costa Rica': '🇨🇷',
  'Panama': '🇵🇦',
  'Honduras': '🇭🇳',
  'Jamaica': '🇯🇲',
  'Trinidad And Tobago': '🇹🇹',
  'Paraguay': '🇵🇾',
  'Bolivia': '🇧🇴',
  'Venezuela': '🇻🇪',
  'Egypt': '🇪🇬',
  'Algeria': '🇩🇿',
  'Congo DR': '🇨🇩',
  'Mali': '🇲🇱',
  'Ivory Coast': '🇨🇮',
  'Cote D\'Ivoire': '🇨🇮',
  'Burkina Faso': '🇧🇫',
  'China': '🇨🇳',
  'India': '🇮🇳',
  'Iraq': '🇮🇶',
  'Uzbekistan': '🇺🇿',
  'Indonesia': '🇮🇩',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'New Zealand': '🇳🇿',
  'Norway': '🇳🇴',
  'Austria': '🇦🇹',
  'Czech Republic': '🇨🇿',
  'Turkey': '🇹🇷',
  'Ukraine': '🇺🇦',
  'Russia': '🇷🇺',
  'Greece': '🇬🇷',
  'Romania': '🇷🇴',
  'Hungary': '🇭🇺',
  'Slovakia': '🇸🇰',
  'Slovenia': '🇸🇮',
  'Albania': '🇦🇱',
  'North Macedonia': '🇲🇰',
  'Georgia': '🇬🇪',
  'Iceland': '🇮🇸',
  'Finland': '🇫🇮',
  'Ireland': '🇮🇪',
  'Bosnia and Herzegovina': '🇧🇦',
  'Montenegro': '🇲🇪',
}

export function getFlag(teamName: string): string {
  return countryFlags[teamName] || '🏳️'
}
