export const countryFlags: Record<string, string> = {
  'Brazil': '🇧🇷',
  'Argentina': '🇦🇷',
  'France': '🇫🇷',
  'Germany': '🇩🇪',
  'Spain': '🇪🇸',
  'Portugal': '🇵🇹',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Mexico': '🇲🇽',
  'USA': '🇺🇸',
  'United States': '🇺🇸',
  'Canada': '🇨🇦',
  'Switzerland': '🇨🇭',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Croatia': '🇭🇷',
  'Uruguay': '🇺🇾',
  'Colombia': '🇨🇴',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'Korea Republic': '🇰🇷',
  'Australia': '🇦🇺',
  'Saudi Arabia': '🇸🇦',
  'Morocco': '🇲🇦',
  'Senegal': '🇸🇳',
  'Ghana': '🇬🇭',
  'Cameroon': '🇨🇲',
  'Nigeria': '🇳🇬',
  'Tunisia': '🇹🇳',
  'Iran': '🇮🇷',
  'Qatar': '🇶🇦',
  'Ecuador': '🇪🇨',
  'Chile': '🇨🇱',
  'Peru': '🇵🇪',
  'Serbia': '🇷🇸',
  'Poland': '🇵🇱',
  'Denmark': '🇩🇰',
  'Sweden': '🇸🇪',
  'Italy': '🇮🇹',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Costa Rica': '🇨🇷',
  'Panama': '🇵🇦',
  'Honduras': '🇭🇳',
  'Jamaica': '🇯🇲',
  'Trinidad And Tobago': '🇹🇹',
  'Paraguay': '🇵🇾',
  'Bolivia': '🇧🇴',
  'Venezuela': '🇻🇪',
  'Egypt': '🇪🇬',
  'Algeria': '🇩🇿',
  'Congo DR': '🇨🇩',
  'Mali': '🇲🇱',
  'Ivory Coast': '🇨🇮',
  'Cote D\'Ivoire': '🇨🇮',
  'Burkina Faso': '🇧🇫',
  'China': '🇨🇳',
  'India': '🇮🇳',
  'Iraq': '🇮🇶',
  'Uzbekistan': '🇺🇿',
  'Indonesia': '🇮🇩',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'New Zealand': '🇳🇿',
  'Norway': '🇳🇴',
  'Austria': '🇦🇹',
  'Czech Republic': '🇨🇿',
  'Turkey': '🇹🇷',
  'Ukraine': '🇺🇦',
  'Russia': '🇷🇺',
  'Greece': '🇬🇷',
  'Romania': '🇷🇴',
  'Hungary': '🇭🇺',
  'Slovakia': '🇸🇰',
  'Slovenia': '🇸🇮',
  'Albania': '🇦🇱',
  'North Macedonia': '🇲🇰',
  'Georgia': '🇬🇪',
  'Iceland': '🇮🇸',
  'Finland': '🇫🇮',
  'Ireland': '🇮🇪',
  'Bosnia and Herzegovina': '🇧🇦',
  'Montenegro': '🇲🇪',
}

export const countryNamesPtBr: Record<string, string> = {
  'Brazil': 'Brasil',
  'Argentina': 'Argentina',
  'France': 'França',
  'Germany': 'Alemanha',
  'Spain': 'Espanha',
  'Portugal': 'Portugal',
  'England': 'Inglaterra',
  'Mexico': 'México',
  'USA': 'EUA',
  'United States': 'Estados Unidos',
  'Canada': 'Canadá',
  'Switzerland': 'Suíça',
  'Netherlands': 'Holanda',
  'Belgium': 'Bélgica',
  'Croatia': 'Croácia',
  'Uruguay': 'Uruguai',
  'Colombia': 'Colômbia',
  'Japan': 'Japão',
  'South Korea': 'Coreia do Sul',
  'Korea Republic': 'Coreia do Sul',
  'Australia': 'Austrália',
  'Saudi Arabia': 'Arábia Saudita',
  'Morocco': 'Marrocos',
  'Senegal': 'Senegal',
  'Ghana': 'Gana',
  'Cameroon': 'Camarões',
  'Nigeria': 'Nigéria',
  'Tunisia': 'Tunísia',
  'Iran': 'Irã',
  'Qatar': 'Catar',
  'Ecuador': 'Equador',
  'Chile': 'Chile',
  'Peru': 'Peru',
  'Serbia': 'Sérvia',
  'Poland': 'Polônia',
  'Denmark': 'Dinamarca',
  'Sweden': 'Suécia',
  'Italy': 'Itália',
  'Wales': 'País de Gales',
  'Scotland': 'Escócia',
  'Costa Rica': 'Costa Rica',
  'Panama': 'Panamá',
  'Honduras': 'Honduras',
  'Jamaica': 'Jamaica',
  'Trinidad And Tobago': 'Trinidad e Tobago',
  'Paraguay': 'Paraguai',
  'Bolivia': 'Bolívia',
  'Venezuela': 'Venezuela',
  'Egypt': 'Egito',
  'Algeria': 'Argélia',
  'Congo DR': 'Congo RD',
  'Mali': 'Mali',
  'Ivory Coast': 'Costa do Marfim',
  'Cote D\'Ivoire': 'Costa do Marfim',
  'Burkina Faso': 'Burkina Faso',
  'China': 'China',
  'India': 'Índia',
  'Iraq': 'Iraque',
  'Uzbekistan': 'Uzbequistão',
  'Indonesia': 'Indonésia',
  'Thailand': 'Tailândia',
  'Vietnam': 'Vietnã',
  'New Zealand': 'Nova Zelândia',
  'Norway': 'Noruega',
  'Austria': 'Áustria',
  'Czech Republic': 'República Tcheca',
  'Turkey': 'Turquia',
  'Ukraine': 'Ucrânia',
  'Russia': 'Rússia',
  'Greece': 'Grécia',
  'Romania': 'Romênia',
  'Hungary': 'Hungria',
  'Slovakia': 'Eslováquia',
  'Slovenia': 'Eslovênia',
  'Albania': 'Albânia',
  'North Macedonia': 'Macedônia do Norte',
  'Georgia': 'Geórgia',
  'Iceland': 'Islândia',
  'Finland': 'Finlândia',
  'Ireland': 'Irlanda',
  'Bosnia and Herzegovina': 'Bósnia e Herzegovina',
  'Montenegro': 'Montenegro',
}

export function getFlag(teamName: string): string {
  return countryFlags[teamName] || '🏳️'
}

export function getTeamNamePtBr(teamName: string | null): string | null {
  if (!teamName) return null
  return countryNamesPtBr[teamName] || teamName
}
